Configura autenticação
Gabrielr2508/recruitment-platform pull request #1
Opened 2019-07-15 16:09 UTC by leolleocomp

## Adições

- Add passport ao projeto:
  - Utiliza _middleware_ para geração de JWT a cada _login_ realizado com sucesso (disponibilizado pelo pacote `laravel/passport`)
  - Uma vez o _login_ realizado com sucesso, o axios "funciona" com rotas protegidas via "auth:api" sem necessidade de configurações adicionais (tudo é feito via http, por "baixo dos panos")
  - O token é válido durante o _lifetime_ da sessão e é sempre enviado via cookie `laravel_token` em requisições subsequentes ao _login_
- Add vuex para armazenamento do estado de autenticação
  - Sempre que a página é recarregada, carrega o estado "auth.authenticated"
  - Sempre que o login é realizado com sucesso, seta "auth.authenticated" para "true"
- Add axios interceptor para respostas com status 401
  - sempre que isso ocorre, força o refresh da página, fazendo com que o estado "auth.authenticated" seja recomputado

2019-07-17 16:29 UTC, gab0gomes requested changes

2019-07-17 16:29 UTC, Gabrielr2508 commented on app/Http/Controllers/LoginController.php
> +		return response('Logou success', 200);
Typo

2019-07-17 16:29 UTC, Gabrielr2508 commented on app/Http/Kernel.php
> +			\Illuminate\Routing\Middleware\SubstituteBindings::class,
Essa indentação ta correta?

2019-07-17 16:29 UTC, Gabrielr2508 commented on composer.json
> +        "jenssegers/mongodb": "3.4.*",
Esse downgrade foi proposital?

2019-07-18 23:20 UTC, leolleocomp commented on composer.json
> +        "jenssegers/mongodb": "3.4.*",
Sim, foi necessário para trabalhar com o pacote [laravel\passport](https://github.com/designmynight/laravel-mongodb-passport), como mostrado no [composer.json](https://github.com/designmynight/laravel-mongodb-passport/blob/master/composer.json#L17) dele.

2019-07-18 23:24 UTC, leolleocomp commented on app/Http/Kernel.php
> +			\Illuminate\Routing\Middleware\SubstituteBindings::class,
Estava inconsistente com o restante do arquivo, havia assumido o uso de tabs. Para garantir o padrão, adicionei um arquivo `php.xml` à raiz do projeto e identei este arquivo de acordo :)

2019-07-18 23:25 UTC, leolleocomp commented on app/Http/Controllers/LoginController.php
> +		return response('Logou success', 200);
Corrigido :)

2019-07-22 13:11 UTC, gab0gomes approved these changes

2019-07-22 13:11 UTC, merged